### ISSUE TITLE
work.html.twig missing

### ISSUE THREAD

**Issue by fugo** [trangthaonguyen/grav-skeleton-timer#1]
I got an error when I used the link _DETAILS_ on the pictures at _Latest Works_.
The ``work.html.twig`` template was missing. I use now the ``default.html.twig``.

**Comment by awrog** [comment]
Really great theme!
Confirmed, work.html.twig is missing.
Te original (free) theme uses [single-portfolio.html](https://github.com/trangthaonguyen/grav-skeleton-timer/files/3329623/single-portfolio.zip)

Unfortunately I'm unable to convert it to twig
